### ISSUE TITLE
Works on objects?

### ISSUE THREAD

**Issue by Acumane** [electrovir/prettier-plugin-newline-arrays#36]
I see you have [tests for objects](https://github.com/electrovir/prettier-plugin-multiline-arrays/blob/main/src/test/typescript-tests.ts), but objects are still being wrapped (default no threshold, `-1`)

**Comment by electrovir** [comment]
Are you saying that object properties are wrapping still? This package does not affect object property wrapping (unless that property is an array).

**Comment by Acumane** [comment]
That's unfortunate. [#2716](https://github.com/prettier/prettier/issues/2716) affects object as well
