### ISSUE TITLE
Update dependency `@augment-vir/common` due to the deprecation of `run-time-assertions`

### ISSUE THREAD

**Issue by SiNONiMiTY** [electrovir/prettier-plugin-newline-arrays#44]
Title. Installation of projects dependent to this plugin will show a deprecation warning since `run-time-assertions` was already deprecated.

**Comment by electrovir** [comment]
resolved in next release

**Comment by electrovir** [comment]
released in [v4.0.0](https://www.npmjs.com/package/prettier-plugin-multiline-arrays/v/4.0.0)
